---
- name: Simple WordPress Installation Test
  hosts: localhost
  become: true
  gather_facts: true
  connection: local

  vars:
    # Basic WordPress configuration
    wordpress_version: "latest"
    wordpress_site_url: "http://localhost:8080"
    wordpress_site_title: "Docker Test Site"
    wordpress_admin_user: "admin"
    wordpress_admin_password: "admin123"
    wordpress_admin_email: "admin@test.local"

    # Database connection (external containers)
    wordpress_use_external_db: true
    wordpress_db_host: "mysql"
    wordpress_db_port: 3306
    wordpress_db_name: "wordpress"
    wordpress_db_user: "wordpress"
    wordpress_db_password: "wordpress"
    wordpress_db_root_password: "root"

    # Web server
    wordpress_web_server: "nginx"
    wordpress_php_version: "8.1"

    # Disable complex features
    wordpress_enable_ssl: false
    wordpress_enable_fail2ban: false
    wordpress_configure_firewall: false
    wordpress_enable_backups: false
    wordpress_enable_monitoring: false
    wordpress_enable_security: false
    wordpress_enable_caching: false

    # System settings
    wordpress_system_user: "www-data"
    wordpress_system_group: "www-data"
    wordpress_install_dependencies: true
    wordpress_update_cache: true
    wordpress_install_dir: "/var/www/wordpress"
    wordpress_file_permissions: "0644"
    wordpress_dir_permissions: "0755"
    wordpress_log_dir: "/var/log/wordpress"
    wordpress_enable_logging: true
    wordpress_install_wpcli: true

    # PHP configuration
    wordpress_php_fpm_service: "php{{ wordpress_php_version }}-fpm"
    wordpress_php_ini_path: "/etc/php/{{ wordpress_php_version }}/fpm/php.ini"
    wordpress_php_fpm_pool_path: "/etc/php/{{ wordpress_php_version }}/fpm/pool.d/www.conf"
    wordpress_php_fpm_user: "{{ wordpress_system_user }}"
    wordpress_php_fpm_group: "{{ wordpress_system_group }}"
    wordpress_php_fpm_listen: "/run/php/php{{ wordpress_php_version }}-fpm.sock"
    wordpress_php_memory_limit: "256M"
    wordpress_php_upload_max_filesize: "64M"
    wordpress_php_post_max_size: "64M"
    wordpress_php_max_execution_time: "300"
    wordpress_php_max_input_time: "600"
    wordpress_php_max_input_vars: "3000"

    # Debug
    wordpress_debug: true
    wordpress_debug_log: true
    wordpress_debug_display: false

  tasks:
    - name: Test external service connectivity
      ansible.builtin.wait_for:
        host: "{{ wordpress_db_host }}"
        port: "{{ wordpress_db_port }}"
        timeout: 30

    - name: Include prerequisites only
      ansible.builtin.include_tasks: tasks/prerequisites.yml

    - name: Include PHP installation
      ansible.builtin.include_tasks: tasks/php.yml

    - name: Include web server installation
      ansible.builtin.include_tasks: tasks/webserver_nginx.yml

    - name: Include WordPress installation
      ansible.builtin.include_tasks: tasks/wordpress_install.yml

    - name: Include WordPress configuration
      ansible.builtin.include_tasks: tasks/wordpress_configure.yml

    - name: Display installation info
      ansible.builtin.debug:
        msg:
          - "WordPress installation test completed!"
          - "Site URL: {{ wordpress_site_url }}"
          - "Admin: {{ wordpress_admin_user }} / {{ wordpress_admin_password }}"
          - "Database: {{ wordpress_db_host }}:{{ wordpress_db_port }}"
