---
- name: Test 5 - Minimal WordPress Installation
  hosts: localhost
  connection: local
  become: yes
  vars:
    # Database configuration for external MySQL
    wordpress_db_name: wordpress
    wordpress_db_user: wordpress
    wordpress_db_password: wordpress123
    wordpress_db_host: wordpress-mysql
    wordpress_db_port: 3306

    # WordPress configuration
    wordpress_install_dir: /var/www/wordpress
    wordpress_url: http://localhost:8080
    wordpress_title: "Test WordPress Site"
    wordpress_admin_user: admin
    wordpress_admin_password: admin123
    wordpress_admin_email: admin@example.com

    # WordPress download
    wordpress_version: latest
    wordpress_download_url: "https://wordpress.org/latest.tar.gz"

    # File permissions
    wordpress_file_permissions: "0644"
    wordpress_dir_permissions: "0755"

    # PHP configuration
    wordpress_php_version: "8.1"

    # Web server configuration
    wordpress_web_server: nginx

    # System user and group
    wordpress_system_user: "www-data"
    wordpress_system_group: "www-data"
    wordpress_php_fpm_user: "www-data"
    wordpress_php_fpm_group: "www-data"

    # Optional features (disable for minimal test)
    wordpress_install_wpcli: false
    wordpress_enable_logging: true
    wordpress_log_dir: "/var/log/wordpress"
    wordpress_error_log: "/var/log/wordpress/error.log"
    wordpress_site_url: "http://localhost:8080"

  tasks:
    - name: Test external database connectivity
      ansible.builtin.wait_for:
        host: "{{ wordpress_db_host }}"
        port: "{{ wordpress_db_port }}"
        timeout: 10

    - name: Install prerequisites only
      ansible.builtin.include_tasks: tasks/prerequisites.yml

    - name: Install WordPress only
      ansible.builtin.include_tasks: tasks/wordpress_install.yml

    - name: Verify WordPress Installation
      block:
        - name: Check WordPress directory exists
          ansible.builtin.stat:
            path: "{{ wordpress_install_dir }}"
          register: wp_dir

        - name: Verify WordPress directory exists
          ansible.builtin.assert:
            that:
              - wp_dir.stat.exists
              - wp_dir.stat.isdir
            fail_msg: "WordPress directory {{ wordpress_install_dir }} does not exist"
            success_msg: "WordPress directory exists: {{ wordpress_install_dir }}"

        - name: Check for WordPress core files
          ansible.builtin.stat:
            path: "{{ wordpress_install_dir }}/{{ item }}"
          register: wp_files
          loop:
            - index.php
            - wp-load.php
            - wp-settings.php
            - wp-blog-header.php

        - name: Verify WordPress core files exist
          ansible.builtin.assert:
            that:
              - item.stat.exists
            fail_msg: "WordPress core file {{ item.item }} is missing"
            success_msg: "WordPress core file {{ item.item }} found"
          loop: "{{ wp_files.results }}"

        - name: Check WordPress directories
          ansible.builtin.stat:
            path: "{{ wordpress_install_dir }}/{{ item }}"
          register: wp_dirs
          loop:
            - wp-content
            - wp-includes
            - wp-admin

        - name: Verify WordPress directories exist
          ansible.builtin.assert:
            that:
              - item.stat.exists
              - item.stat.isdir
            fail_msg: "WordPress directory {{ item.item }} is missing"
            success_msg: "WordPress directory {{ item.item }} found"
          loop: "{{ wp_dirs.results }}"

        - name: Count WordPress PHP files
          ansible.builtin.find:
            paths: "{{ wordpress_install_dir }}"
            patterns: "*.php"
          register: wp_php_files

        - name: Display installation summary
          ansible.builtin.debug:
            msg:
              - "=== WordPress Installation Test Results ==="
              - "✓ WordPress directory: {{ wordpress_install_dir }}"
              - "✓ Core PHP files: {{ wp_files.results | selectattr('stat.exists') |
                list | length }}/{{ wp_files.results | length }}"
              - "✓ Core directories: {{ wp_dirs.results | selectattr('stat.exists') |
                selectattr('stat.isdir') | list | length }}/{{ wp_dirs.results | length }}"
              - "✓ Total PHP files found: {{ wp_php_files.files | length }}"
              - "✓ Database host: {{ wordpress_db_host }} (connection verified)"
              - "✓ Installation completed successfully!"
