---
- name: Test 4 - Complete WordPress Installation with Verification
  hosts: localhost
  connection: local
  become: yes
  vars:
    # Database configuration for external MySQL
    wordpress_db_name: wordpress
    wordpress_db_user: wordpress
    wordpress_db_password: wordpress123
    wordpress_db_host: wordpress-mysql
    wordpress_db_port: 3306

    # WordPress configuration
    wordpress_install_dir: /var/www/wordpress
    wordpress_url: http://localhost:8080
    wordpress_title: "Test WordPress Site"
    wordpress_admin_user: admin
    wordpress_admin_password: admin123
    wordpress_admin_email: admin@example.com

    # WordPress download
    wordpress_version: latest
    wordpress_download_url: "https://wordpress.org/latest.tar.gz"

    # File permissions
    wordpress_file_permissions: "0644"
    wordpress_dir_permissions: "0755"

    # PHP configuration
    wordpress_php_version: "8.1"

    # Web server configuration
    wordpress_web_server: nginx

    # Simplified configuration - disable complex features for testing
    wordpress_ssl_enabled: false
    wordpress_fail2ban_enabled: false
    wordpress_firewall_enabled: false
    wordpress_backup_enabled: false
    wordpress_monitoring_enabled: false
    wordpress_security_hardening: false
    wordpress_caching_enabled: false

  tasks:
    - name: Test external database connectivity
      wait_for:
        host: "{{ wordpress_db_host }}"
        port: "{{ wordpress_db_port }}"
        timeout: 10

    - name: Install prerequisites
      include_tasks: tasks/prerequisites.yml

    - name: Install and configure PHP
      include_tasks: tasks/php.yml

    - name: Install and configure web server
      include_tasks: tasks/webserver.yml

    - name: Install WordPress
      include_tasks: tasks/wordpress_install.yml

    - name: Configure WordPress
      include_tasks: tasks/wordpress_config.yml

    - name: Verify WordPress Installation
      block:
        - name: Check WordPress directory exists
          stat:
            path: "{{ wordpress_install_dir }}"
          register: wp_dir

        - name: Verify WordPress directory exists
          assert:
            that:
              - wp_dir.stat.exists
              - wp_dir.stat.isdir
            fail_msg: "WordPress directory {{ wordpress_install_dir }} does not exist"
            success_msg: "WordPress directory exists"

        - name: Check for WordPress core files
          stat:
            path: "{{ wordpress_install_dir }}/{{ item }}"
          register: wp_files
          loop:
            - wp-config.php
            - index.php
            - wp-load.php
            - wp-settings.php
            - wp-blog-header.php

        - name: Verify WordPress core files exist
          assert:
            that:
              - item.stat.exists
            fail_msg: "WordPress core file {{ item.item }} is missing"
            success_msg: "WordPress core file {{ item.item }} exists"
          loop: "{{ wp_files.results }}"

        - name: Check WordPress directories
          stat:
            path: "{{ wordpress_install_dir }}/{{ item }}"
          register: wp_dirs
          loop:
            - wp-content
            - wp-includes
            - wp-admin

        - name: Verify WordPress directories exist
          assert:
            that:
              - item.stat.exists
              - item.stat.isdir
            fail_msg: "WordPress directory {{ item.item }} is missing"
            success_msg: "WordPress directory {{ item.item }} exists"
          loop: "{{ wp_dirs.results }}"

        - name: Check file ownership
          stat:
            path: "{{ wordpress_install_dir }}/index.php"
          register: wp_ownership

        - name: Verify file ownership
          assert:
            that:
              - wp_ownership.stat.pw_name == "www-data"
              - wp_ownership.stat.gr_name == "www-data"
            fail_msg: "WordPress files do not have correct ownership (www-data:www-data)"
            success_msg: "WordPress files have correct ownership"

        - name: Display installation summary
          debug:
            msg:
              - "WordPress installation completed successfully!"
              - "Installation directory: {{ wordpress_install_dir }}"
              - "WordPress URL: {{ wordpress_url }}"
              - "Database host: {{ wordpress_db_host }}"
              - "Web server: {{ wordpress_web_server }}"
              - "PHP version: {{ wordpress_php_version }}"

        - name: List installed WordPress files (sample)
          find:
            paths: "{{ wordpress_install_dir }}"
            patterns: "wp-*.php"
          register: wp_core_files

        - name: Show WordPress core files
          debug:
            msg: "Found {{ wp_core_files.files | length }} WordPress core PHP files"

        - name: Check wp-config.php content
          lineinfile:
            path: "{{ wordpress_install_dir }}/wp-config.php"
            line: "define( 'DB_NAME', '{{ wordpress_db_name }}' );"
            state: present
          check_mode: yes
          register: wp_config_check

        - name: Verify wp-config.php is properly configured
          assert:
            that:
              - not wp_config_check.changed
            fail_msg: "wp-config.php is not properly configured with database settings"
            success_msg: "wp-config.php is properly configured"
