---
- name: Test 1 - Basic Prerequisites Installation
  hosts: localhost
  become: true
  gather_facts: true
  connection: local
  
  vars:
    wordpress_system_user: "www-data"
    wordpress_system_group: "www-data"
    wordpress_install_dir: "/var/www/wordpress"
    wordpress_log_dir: "/var/log/wordpress"
    wordpress_enable_logging: true
    
  tasks:
    - name: Test Prerequisites Installation
      include_tasks: tasks/prerequisites.yml
      
    - name: Verify basic packages are installed
      command: which {{ item }}
      loop:
        - curl
        - wget
        - unzip
        - git
      register: package_check
      changed_when: false
      
    - name: Display test results
      debug:
        msg: 
          - "✅ Prerequisites test completed successfully!"
          - "✅ All basic packages are installed"
          - "✅ WordPress directories created"
          - "✅ System user created: {{ wordpress_system_user }}"