---
- name: Test WordPress Installation in Docker
  hosts: localhost
  become: true
  gather_facts: true
  connection: local

  vars:
    # Simple configuration for Docker testing
    wordpress_version: "latest"
    wordpress_site_url: "http://localhost:8080"
    wordpress_site_title: "Docker WordPress Test"
    wordpress_admin_user: "admin"
    wordpress_admin_password: "admin123"
    wordpress_admin_email: "admin@test.local"

    # Use external database (already running in Docker)
    wordpress_use_external_db: true
    wordpress_db_host: "mysql"  # Use service name from docker-compose
    wordpress_db_port: 3306
    wordpress_db_name: "wordpress"
    wordpress_db_user: "wordpress"
    wordpress_db_password: "wordpress"
    wordpress_db_root_password: "root"

    # Web server configuration
    wordpress_web_server: "nginx"
    wordpress_php_version: "8.2"
    wordpress_php_memory_limit: "256M"

    # Cache configuration (external service)
    wordpress_enable_redis: true
    wordpress_redis_host: "redis"  # Use service name from docker-compose
    wordpress_redis_port: 6379
    wordpress_enable_object_cache: true

    # Disable complex features for Docker testing
    wordpress_enable_ssl: false
    wordpress_enable_fail2ban: false
    wordpress_configure_firewall: false
    wordpress_enable_backups: false
    wordpress_enable_monitoring: false
    wordpress_enable_security: false
    wordpress_enable_caching: true

    # Debug mode for testing
    wordpress_debug: true
    wordpress_debug_log: true
    wordpress_debug_display: false

    # Allow file editing in test environment
    wordpress_disable_file_edit: false
    wordpress_disable_file_mods: false

    # System users
    wordpress_system_user: "www-data"
    wordpress_system_group: "www-data"

  tasks:
    - name: Test database connectivity
      ansible.builtin.wait_for:
        host: "{{ wordpress_db_host }}"
        port: "{{ wordpress_db_port }}"
        timeout: 30
      when: wordpress_use_external_db | default(false) | bool

    - name: Test Redis connectivity
      ansible.builtin.wait_for:
        host: "{{ wordpress_redis_host }}"
        port: "{{ wordpress_redis_port }}"
        timeout: 30
      when: wordpress_use_external_cache | default(false) | bool

  roles:
    - role: .
      # Use the current directory as the role

  post_tasks:
    - name: Display WordPress site information
      ansible.builtin.debug:
        msg:
          - "WordPress installation completed!"
          - "Site URL: {{ wordpress_site_url }}"
          - "Admin URL: {{ wordpress_site_url }}/wp-admin/"
          - "Username: {{ wordpress_admin_user }}"
          - "Password: {{ wordpress_admin_password }}"
          - "Database: {{ wordpress_db_host }}:{{ wordpress_db_port }}"
          - "Cache: {{ wordpress_redis_host }}:{{ wordpress_redis_port }}"
