---
- name: Test 2 - PHP Installation (PHP 8.1)
  hosts: localhost
  become: true
  gather_facts: true
  connection: local

  vars:
    wordpress_system_user: "www-data"
    wordpress_system_group: "www-data"
    wordpress_install_dir: "/var/www/wordpress"
    wordpress_log_dir: "/var/log/wordpress"
    wordpress_enable_logging: true

    # PHP 8.1 configuration
    wordpress_php_version: "8.1"
    wordpress_php_fpm_service: "php8.1-fpm"
    wordpress_php_ini_path: "/etc/php/8.1/fpm/php.ini"
    wordpress_php_fpm_pool_path: "/etc/php/8.1/fpm/pool.d/www.conf"
    wordpress_php_fpm_user: "www-data"
    wordpress_php_fmp_group: "www-data"
    wordpress_php_fpm_listen: "/run/php/php8.1-fpm.sock"
    wordpress_php_memory_limit: "256M"
    wordpress_php_upload_max_filesize: "64M"
    wordpress_php_post_max_size: "64M"
    wordpress_php_max_execution_time: "300"
    wordpress_php_max_input_time: "600"
    wordpress_php_max_input_vars: "3000"

  tasks:
    - name: Install Prerequisites
      include_tasks: tasks/prerequisites.yml

    - name: Install PHP
      include_tasks: tasks/php.yml

    - name: Verify PHP installation
      command: php{{ wordpress_php_version }} --version
      register: php_version
      changed_when: false

    - name: Check PHP-FPM service status
      systemd:
        name: "{{ wordpress_php_fpm_service }}"
        state: started
      register: php_fpm_status

    - name: Verify PHP extensions
      command: php{{ wordpress_php_version }} -m
      register: php_modules
      changed_when: false

    - name: Display PHP test results
      debug:
        msg:
          - "✅ PHP {{ wordpress_php_version }} installation completed!"
          - "✅ PHP version: {{ php_version.stdout.split('\n')[0] }}"
          - "✅ PHP-FPM service: {{ wordpress_php_fpm_service }} is running"
          - "✅ Required extensions installed"
