---
- name: Test 2 - PHP Installation (No Handlers)
  hosts: localhost
  become: true
  gather_facts: true
  connection: local

  vars:
    wordpress_system_user: "www-data"
    wordpress_system_group: "www-data"
    wordpress_install_dir: "/var/www/wordpress"
    wordpress_log_dir: "/var/log/wordpress"
    wordpress_enable_logging: true
    wordpress_php_version: "8.1"

  tasks:
    - name: Install Prerequisites
      ansible.builtin.include_tasks: tasks/prerequisites.yml

    - name: Install PHP packages
      ansible.builtin.apt:
        name:
          - "php{{ wordpress_php_version }}"
          - "php{{ wordpress_php_version }}-fpm"
          - "php{{ wordpress_php_version }}-mysql"
          - "php{{ wordpress_php_version }}-curl"
          - "php{{ wordpress_php_version }}-gd"
          - "php{{ wordpress_php_version }}-mbstring"
          - "php{{ wordpress_php_version }}-xml"
          - "php{{ wordpress_php_version }}-xmlrpc"
          - "php{{ wordpress_php_version }}-soap"
          - "php{{ wordpress_php_version }}-intl"
          - "php{{ wordpress_php_version }}-zip"
          - "php{{ wordpress_php_version }}-bcmath"
          - "php{{ wordpress_php_version }}-imagick"
        state: present
        update_cache: true

    - name: Enable and start PHP-FPM service
      ansible.builtin.systemd:
        name: "php{{ wordpress_php_version }}-fpm"
        enabled: true
        state: started
        daemon_reload: true

    - name: Verify PHP installation
      ansible.builtin.command: "php{{ wordpress_php_version }} --version"
      register: php_version
      changed_when: false

    - name: Check PHP-FPM service status
      ansible.builtin.systemd:
        name: "php{{ wordpress_php_version }}-fpm"
        state: started
      register: php_fmp_status

    - name: Display test results
      ansible.builtin.debug:
        msg:
          - "✅ PHP {{ wordpress_php_version }} installation completed!"
          - "✅ PHP version: {{ php_version.stdout.split('\\n')[0] }}"
          - "✅ PHP-FPM service is running"
