---
- name: Test 3 - Complete WordPress Installation
  hosts: localhost
  become: true
  gather_facts: true
  connection: local

  vars:
    # WordPress configuration
    wordpress_version: "latest"
    wordpress_site_url: "http://localhost:8080"
    wordpress_site_title: "Complete WordPress Test"
    wordpress_admin_user: "admin"
    wordpress_admin_password: "admin123"
    wordpress_admin_email: "admin@test.local"

    # External database
    wordpress_use_external_db: true
    wordpress_db_host: "mysql"
    wordpress_db_port: 3306
    wordpress_db_name: "wordpress"
    wordpress_db_user: "wordpress"
    wordpress_db_password: "wordpress"

    # System configuration
    wordpress_system_user: "www-data"
    wordpress_system_group: "www-data"
    wordpress_install_dir: "/var/www/wordpress"
    wordpress_log_dir: "/var/log/wordpress"
    wordpress_enable_logging: true
    wordpress_file_permissions: "0644"
    wordpress_dir_permissions: "0755"
    wordpress_download_url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"

    # PHP configuration
    wordpress_php_version: "8.1"
    wordpress_php_memory_limit: "256M"

    # Web server
    wordpress_web_server: "nginx"

    # Disable complex features for testing
    wordpress_enable_ssl: false
    wordpress_enable_fail2ban: false
    wordpress_configure_firewall: false
    wordpress_enable_backups: false
    wordpress_enable_monitoring: false
    wordpress_enable_security: false
    wordpress_enable_caching: false

    # WP-CLI
    wordpress_install_wpcli: true

  tasks:
    - name: Test external database connectivity
      wait_for:
        host: "{{ wordpress_db_host }}"
        port: "{{ wordpress_db_port }}"
        timeout: 30

    - name: Install prerequisites
      include_tasks: tasks/prerequisites.yml

    - name: Install WordPress
      include_tasks: tasks/wordpress_install.yml

    - name: Download latest WordPress (simplified)
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"
        mode: '0644'
        timeout: 300
      register: wp_download

    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/tmp"
        remote_src: true

    - name: Copy WordPress files
      copy:
        src: "/tmp/wordpress/"
        dest: "{{ wordpress_install_dir }}/"
        remote_src: true
        owner: "{{ wordpress_system_user }}"
        group: "{{ wordpress_system_group }}"
        mode: preserve

    - name: Create wp-config.php from template
      template:
        src: wp-config.php.j2
        dest: "{{ wordpress_install_dir }}/wp-config.php"
        owner: "{{ wordpress_system_user }}"
        group: "{{ wordpress_system_group }}"
        mode: '0600'

    - name: Verify WordPress files exist
      stat:
        path: "{{ item }}"
      loop:
        - "{{ wordpress_install_dir }}/wp-config.php"
        - "{{ wordpress_install_dir }}/wp-load.php"
        - "{{ wordpress_install_dir }}/index.php"
      register: wp_files_check

    - name: Display WordPress installation results
      debug:
        msg:
          - "✅ Complete WordPress installation test completed!"
          - "✅ WordPress downloaded and extracted"
          - "✅ wp-config.php created"
          - "✅ All core WordPress files present"
          - "✅ Database connectivity tested"
