---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for system to be ready
      ansible.builtin.wait_for_connection:
        timeout: 60
    
    - name: Install python for Ansible
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3-minimal)
      changed_when: false
      failed_when: false