---
##
# Cloudflare-Only WordPress Deployment
# Uses Cloudflare for DNS, CDN, and DDoS protection
# Local database and cache
##

- name: Deploy WordPress with Cloudflare Integration
  hosts: wordpress_servers
  become: true
  gather_facts: true

  vars_files:
    - vault.yml

  vars:
    # ========================================================================
    # WordPress Core
    # ========================================================================
    wordpress_version: "6.4.2"
    wordpress_site_url: "https://example.com"
    wordpress_site_title: "My Cloudflare-Protected Site"
    wordpress_admin_user: "{{ vault_wp_admin_user }}"
    wordpress_admin_password: "{{ vault_wp_admin_password }}"
    wordpress_admin_email: "admin@example.com"

    # ========================================================================
    # Infrastructure
    # ========================================================================
    wordpress_web_server: "nginx"
    wordpress_php_version: "8.2"
    wordpress_db_engine: "mariadb"

    # Local database
    wordpress_use_external_db: false
    wordpress_db_name: "wordpress"
    wordpress_db_user: "wordpress"
    wordpress_db_password: "{{ vault_wp_db_password }}"

    # ========================================================================
    # Cloudflare Configuration
    # ========================================================================
    wordpress_cloud_provider: "cloudflare"
    wordpress_cloudflare_enabled: true
    wordpress_cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
    wordpress_cloudflare_zone_id: "{{ vault_cloudflare_zone_id }}"
    wordpress_cloudflare_email: "cloudflare@example.com"

    # DNS Management
    wordpress_cloudflare_dns_records:
      - name: "example.com"
        type: "A"
        value: "{{ ansible_default_ipv4.address }}"
        proxied: true
        ttl: 1

      - name: "www.example.com"
        type: "CNAME"
        value: "example.com"
        proxied: true
        ttl: 1

    # Cloudflare CDN & Caching
    wordpress_cloudflare_cdn_enabled: true
    wordpress_cloudflare_cache_ttl: 14400
    wordpress_cloudflare_purge_on_update: true

    # ========================================================================
    # Local Caching
    # ========================================================================
    wordpress_enable_redis: true
    wordpress_redis_host: "127.0.0.1"
    wordpress_redis_port: 6379

    # ========================================================================
    # SSL/TLS (Cloudflare Flexible/Full)
    # ========================================================================
    wordpress_enable_ssl: true
    wordpress_use_letsencrypt: true
    wordpress_letsencrypt_email: "ssl@example.com"

    # ========================================================================
    # Security
    # ========================================================================
    wordpress_enable_fail2ban: true
    wordpress_configure_firewall: true
    wordpress_disable_file_edit: true

    # ========================================================================
    # Plugins
    # ========================================================================
    wordpress_plugins:
      - name: "wordfence"
        version: "latest"
        state: "present"
      - name: "wp-super-cache"
        version: "latest"
        state: "present"
      - name: "wordpress-seo"
        version: "latest"
        state: "present"

  roles:
    - role: thomasvincent.wordpress_enterprise
