---
##
# Google Cloud Platform WordPress Deployment
# Uses Cloud SQL, Memorystore Redis, Cloud Storage, and Cloud CDN
##

- name: Deploy WordPress on Google Cloud Platform
  hosts: wordpress_servers
  become: true
  gather_facts: true

  vars_files:
    - vault.yml

  vars:
    # ========================================================================
    # WordPress Core
    # ========================================================================
    wordpress_version: "6.4.2"
    wordpress_site_url: "https://blog.example.com"
    wordpress_site_title: "GCP-Powered WordPress"
    wordpress_admin_user: "{{ vault_wp_admin_user }}"
    wordpress_admin_password: "{{ vault_wp_admin_password }}"
    wordpress_admin_email: "admin@example.com"

    # ========================================================================
    # Infrastructure
    # ========================================================================
    wordpress_web_server: "nginx"
    wordpress_php_version: "8.2"
    wordpress_php_memory_limit: "512M"
    wordpress_php_upload_max_filesize: "256M"

    # ========================================================================
    # Cloud Provider
    # ========================================================================
    wordpress_cloud_provider: "google"
    wordpress_gcp_enabled: true
    wordpress_gcp_project_id: "{{ vault_gcp_project_id }}"
    wordpress_gcp_service_account_key: "{{ vault_gcp_sa_key }}"

    # ========================================================================
    # Google Cloud SQL (Managed MySQL)
    # ========================================================================
    wordpress_use_external_db: true
    wordpress_db_engine: "mysql"
    wordpress_gcp_cloudsql_enabled: true
    wordpress_gcp_cloudsql_instance: "{{ vault_gcp_cloudsql_instance }}"
    wordpress_external_db_type: "cloud_sql"

    # Private IP connection
    wordpress_external_db_host: "10.0.0.3"
    wordpress_external_db_port: 3306
    wordpress_external_db_name: "wordpress"
    wordpress_external_db_user: "{{ vault_gcp_db_user }}"
    wordpress_external_db_password: "{{ vault_gcp_db_password }}"
    wordpress_external_db_ssl_enabled: true

    # Cloud SQL Proxy
    wordpress_gcp_cloudsql_proxy_enabled: true

    # ========================================================================
    # Google Cloud Memorystore (Managed Redis)
    # ========================================================================
    wordpress_use_external_cache: true
    wordpress_enable_redis: true
    wordpress_gcp_memorystore_enabled: true
    wordpress_gcp_memorystore_instance: "{{ vault_gcp_memorystore_instance }}"
    wordpress_gcp_memorystore_host: "10.0.0.4"
    wordpress_gcp_memorystore_port: 6379
    wordpress_enable_object_cache: true

    # ========================================================================
    # Google Cloud Storage
    # ========================================================================
    wordpress_object_storage_enabled: true
    wordpress_object_storage_provider: "gcs"
    wordpress_gcp_storage_enabled: true
    wordpress_gcp_storage_bucket: "{{ vault_gcp_storage_bucket }}"
    wordpress_object_storage_bucket: "{{ vault_gcp_storage_bucket }}"
    wordpress_object_storage_path_prefix: "wp-content/uploads"

    # Google Cloud CDN
    wordpress_gcp_cdn_enabled: true
    wordpress_cdn_enabled: true
    wordpress_cdn_provider: "google"
    wordpress_cdn_domain: "cdn.example.com"

    # ========================================================================
    # SSL/TLS
    # ========================================================================
    wordpress_enable_ssl: true
    wordpress_use_letsencrypt: true
    wordpress_letsencrypt_email: "ssl@example.com"
    wordpress_ssl_protocols: "TLSv1.2 TLSv1.3"

    # ========================================================================
    # Email - SendGrid
    # ========================================================================
    wordpress_smtp_enabled: true
    wordpress_smtp_provider: "sendgrid"
    wordpress_smtp_host: "smtp.sendgrid.net"
    wordpress_smtp_port: 587
    wordpress_smtp_user: "apikey"
    wordpress_smtp_password: "{{ vault_sendgrid_api_key }}"
    wordpress_smtp_from_email: "noreply@example.com"
    wordpress_smtp_encryption: "tls"

    # ========================================================================
    # Performance Optimization
    # ========================================================================
    wordpress_opcache_enable: true
    wordpress_opcache_memory: "256"
    wordpress_opcache_validate_timestamps: "0"

    wordpress_image_optimization_enabled: true
    wordpress_webp_enabled: true
    wordpress_avif_enabled: true

    wordpress_http2_push_enabled: true
    wordpress_http2_push_preload: true

    # ========================================================================
    # Security
    # ========================================================================
    wordpress_enable_fail2ban: true
    wordpress_configure_firewall: true
    wordpress_disable_file_edit: true
    wordpress_force_ssl_admin: true
    wordpress_disallow_unfiltered_html: true

    # ========================================================================
    # Backups to Cloud Storage
    # ========================================================================
    wordpress_enable_backups: true
    wordpress_backup_dir: "/var/backups/wordpress"
    wordpress_backup_retention_days: 30
    wordpress_backup_to_cloud: true
    wordpress_backup_cloud_provider: "gcs"
    wordpress_backup_cloud_bucket: "wordpress-backups-{{ vault_gcp_project_id }}"

    # ========================================================================
    # Monitoring & Logging (GCP Stackdriver)
    # ========================================================================
    wordpress_enable_logging: true
    wordpress_log_dir: "/var/log/wordpress"
    wordpress_logrotate_enabled: true

    # ========================================================================
    # Plugins
    # ========================================================================
    wordpress_plugins:
      - name: "wordfence"
        version: "latest"
        state: "present"
      - name: "redis-cache"
        version: "latest"
        state: "present"
      - name: "gcs"  # Google Cloud Storage plugin
        version: "latest"
        state: "present"
      - name: "wp-mail-smtp"
        version: "latest"
        state: "present"
      - name: "wordpress-seo"
        version: "latest"
        state: "present"
      - name: "updraftplus"
        version: "latest"
        state: "present"
      - name: "ewww-image-optimizer"
        version: "latest"
        state: "present"

    # ========================================================================
    # Themes
    # ========================================================================
    wordpress_themes:
      - name: "astra"
        version: "latest"
        state: "present"
        activate: true

  roles:
    - role: thomasvincent.wordpress_enterprise
