---
##
# Local Development WordPress Deployment
# Minimal configuration for local testing and development
# No cloud services, self-signed SSL, debug enabled
##

- name: Deploy WordPress for Local Development
  hosts: localhost
  become: true
  gather_facts: true
  connection: local

  vars:
    # ========================================================================
    # WordPress Core
    # ========================================================================
    wordpress_version: "latest"  # Always use latest in dev
    wordpress_site_url: "https://wordpress.local"
    wordpress_site_title: "WordPress Development Site"
    wordpress_admin_user: "admin"
    wordpress_admin_password: "admin123"  # Weak password OK for local dev
    wordpress_admin_email: "admin@wordpress.local"

    # ========================================================================
    # Infrastructure
    # ========================================================================
    wordpress_web_server: "nginx"
    wordpress_php_version: "8.2"
    wordpress_php_memory_limit: "256M"

    # ========================================================================
    # Local Database
    # ========================================================================
    wordpress_use_external_db: false
    wordpress_db_engine: "mariadb"
    wordpress_db_name: "wordpress_dev"
    wordpress_db_user: "wordpress"
    wordpress_db_password: "wordpress"
    wordpress_db_root_password: "root"

    # ========================================================================
    # Local Cache
    # ========================================================================
    wordpress_enable_redis: true
    wordpress_redis_host: "127.0.0.1"
    wordpress_redis_port: 6379
    wordpress_enable_object_cache: true

    # ========================================================================
    # Cloud Provider
    # ========================================================================
    wordpress_cloud_provider: "none"  # No cloud services

    # ========================================================================
    # SSL/TLS - Self-Signed Certificate
    # ========================================================================
    wordpress_enable_ssl: true
    wordpress_use_letsencrypt: false
    wordpress_generate_self_signed_cert: true
    wordpress_ssl_certificate: "/etc/ssl/certs/wordpress-dev.crt"
    wordpress_ssl_certificate_key: "/etc/ssl/private/wordpress-dev.key"

    # ========================================================================
    # Development Settings
    # ========================================================================
    # Enable debugging
    wordpress_debug: true
    wordpress_debug_log: true
    wordpress_debug_display: true

    # Allow file editing
    wordpress_disable_file_edit: false
    wordpress_disable_file_mods: false

    # ========================================================================
    # Email - Local SMTP (MailHog/MailCatcher)
    # ========================================================================
    wordpress_smtp_enabled: true
    wordpress_smtp_provider: "smtp"
    wordpress_smtp_host: "127.0.0.1"
    wordpress_smtp_port: 1025  # MailHog default port
    wordpress_smtp_user: ""
    wordpress_smtp_password: ""
    wordpress_smtp_from_email: "dev@wordpress.local"
    wordpress_smtp_encryption: "none"
    wordpress_smtp_auth: false

    # ========================================================================
    # Performance - Relaxed for Development
    # ========================================================================
    wordpress_opcache_enable: true
    wordpress_opcache_memory: "128"
    wordpress_opcache_validate_timestamps: "1"  # Revalidate every request

    # Disable image optimization (faster in dev)
    wordpress_image_optimization_enabled: false
    wordpress_webp_enabled: false

    # ========================================================================
    # Security - Relaxed for Development
    # ========================================================================
    wordpress_enable_fail2ban: false
    wordpress_configure_firewall: false
    wordpress_force_ssl_admin: false

    # ========================================================================
    # Backups - Disabled for Development
    # ========================================================================
    wordpress_enable_backups: false

    # ========================================================================
    # Monitoring - Minimal
    # ========================================================================
    wordpress_enable_logging: true
    wordpress_log_dir: "/var/log/wordpress"

    # ========================================================================
    # Plugins - Development Tools
    # ========================================================================
    wordpress_plugins:
      - name: "query-monitor"  # Debug queries
        version: "latest"
        state: "present"

      - name: "debug-bar"
        version: "latest"
        state: "present"

      - name: "developer"  # Development tools
        version: "latest"
        state: "present"

      - name: "regenerate-thumbnails"
        version: "latest"
        state: "present"

      - name: "wp-mail-smtp"
        version: "latest"
        state: "present"

      # Optional: Still install security plugins for testing
      - name: "wordfence"
        version: "latest"
        state: "absent"  # Not needed in dev

    # ========================================================================
    # Themes - Default Theme
    # ========================================================================
    wordpress_themes:
      - name: "twentytwentyfour"
        version: "latest"
        state: "present"
        activate: true

    # ========================================================================
    # Additional Development Constants
    # ========================================================================
    wordpress_additional_constants:
      WP_ENVIRONMENT_TYPE: "development"
      SCRIPT_DEBUG: true
      SAVEQUERIES: true
      WP_DISABLE_FATAL_ERROR_HANDLER: true

  pre_tasks:
    - name: Add wordpress.local to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 wordpress.local"
        state: present
      become: true

    - name: Install MailHog for local email testing (optional)
      ansible.builtin.debug:
        msg: |
          To install MailHog for email testing:
          brew install mailhog  # macOS
          sudo apt install mailhog  # Ubuntu
          Then run: mailhog

  roles:
    - role: thomasvincent.wordpress_enterprise

  post_tasks:
    - name: Display development site information
      ansible.builtin.debug:
        msg:
          - "=== WordPress Development Site Ready ==="
          - "Site URL: {{ wordpress_site_url }}"
          - "Admin URL: {{ wordpress_site_url }}/wp-admin"
          - "Username: {{ wordpress_admin_user }}"
          - "Password: {{ wordpress_admin_password }}"
          - ""
          - "Database: localhost:3306"
          - "DB Name: {{ wordpress_db_name }}"
          - "DB User: {{ wordpress_db_user }}"
          - "DB Password: {{ wordpress_db_password }}"
          - ""
          - "Redis: localhost:6379"
          - ""
          - "Email Testing: http://localhost:8025 (MailHog)"
          - ""
          - "Debug Mode: ENABLED"
          - "Debug Log: {{ wordpress_log_dir }}/debug.log"
          - ""
          - "NOTE: Self-signed SSL certificate - accept browser warning"
          - "Add to /etc/hosts: 127.0.0.1 wordpress.local"

    - name: Open browser (macOS)
      ansible.builtin.command:
        cmd: "open {{ wordpress_site_url }}"
      when: ansible_os_family == "Darwin"
      failed_when: false
      changed_when: false
