---
##
# Oracle Cloud Infrastructure WordPress Deployment
# Uses OCI Compute, Autonomous Database, Block Storage, Load Balancer, and Object Storage
# Optimized for OCI Free Tier and PAUSATF deployments
##

- name: Deploy WordPress on Oracle Cloud Infrastructure
  hosts: wordpress_servers
  become: true
  gather_facts: true

  vars_files:
    - vault.yml

  vars:
    # ========================================================================
    # WordPress Core
    # ========================================================================
    wordpress_version: "6.4.2"
    wordpress_site_url: "https://blog.example.com"
    wordpress_site_title: "OCI-Powered WordPress"
    wordpress_admin_user: "{{ vault_wp_admin_user }}"
    wordpress_admin_password: "{{ vault_wp_admin_password }}"
    wordpress_admin_email: "admin@example.com"

    # ========================================================================
    # Infrastructure
    # ========================================================================
    wordpress_web_server: "nginx"
    wordpress_php_version: "8.2"
    wordpress_php_memory_limit: "512M"
    wordpress_php_upload_max_filesize: "256M"

    # ========================================================================
    # Cloud Provider
    # ========================================================================
    wordpress_cloud_provider: "oracle"
    wordpress_oci_enabled: true
    wordpress_oci_tenancy: "{{ vault_oci_tenancy }}"
    wordpress_oci_user: "{{ vault_oci_user }}"
    wordpress_oci_fingerprint: "{{ vault_oci_fingerprint }}"
    wordpress_oci_key_file: "/home/{{ ansible_user }}/.oci/oci_api_key.pem"
    wordpress_oci_region: "us-ashburn-1"

    # ========================================================================
    # OCI Compute Instance Configuration
    # ========================================================================
    wordpress_oci_compartment_id: "{{ vault_oci_compartment_id }}"
    wordpress_oci_availability_domain: "{{ vault_oci_availability_domain }}"
    wordpress_oci_subnet_id: "{{ vault_oci_subnet_id }}"
    wordpress_oci_shape: "VM.Standard.E4.Flex"
    wordpress_oci_ocpus: 2
    wordpress_oci_memory_gb: 16
    wordpress_oci_boot_volume_size_gb: 50

    # ========================================================================
    # OCI Block Storage for Persistent Data
    # ========================================================================
    wordpress_oci_block_storage_enabled: true
    wordpress_oci_block_volume_size_gb: 100
    wordpress_oci_block_volume_performance: "Balanced"
    wordpress_oci_block_volume_mount_point: "/var/www/wordpress"
    wordpress_oci_block_volume_backup_policy: "bronze"

    # ========================================================================
    # OCI Load Balancer Integration
    # ========================================================================
    wordpress_oci_load_balancer_enabled: true
    wordpress_oci_lb_shape: "flexible"
    wordpress_oci_lb_min_bandwidth_mbps: 10
    wordpress_oci_lb_max_bandwidth_mbps: 100
    wordpress_oci_lb_backend_set_policy: "ROUND_ROBIN"
    wordpress_oci_lb_health_check_path: "/wp-admin/install.php"
    wordpress_oci_lb_health_check_port: 443

    # ========================================================================
    # OCI Autonomous Database (MySQL)
    # ========================================================================
    wordpress_use_external_db: true
    wordpress_db_engine: "mysql"
    wordpress_external_db_type: "oracle_db"
    wordpress_external_db_host: "{{ vault_oci_db_host }}"
    wordpress_external_db_port: 3306
    wordpress_external_db_name: "wordpress"
    wordpress_external_db_user: "{{ vault_oci_db_user }}"
    wordpress_external_db_password: "{{ vault_oci_db_password }}"
    wordpress_external_db_ssl_enabled: true
    wordpress_external_db_ssl_ca: "/etc/ssl/certs/oci-db-ca.crt"

    # ========================================================================
    # Local Redis (or use OCI Cache if available)
    # ========================================================================
    wordpress_enable_redis: true
    wordpress_redis_host: "127.0.0.1"
    wordpress_redis_port: 6379
    wordpress_enable_object_cache: true

    # ========================================================================
    # OCI Object Storage for Media and Backups
    # ========================================================================
    wordpress_object_storage_enabled: true
    wordpress_object_storage_provider: "oci_storage"
    wordpress_oci_object_storage_enabled: true
    wordpress_oci_object_storage_bucket: "{{ vault_oci_bucket_name }}"
    wordpress_oci_object_storage_namespace: "{{ vault_oci_namespace }}"
    wordpress_oci_object_storage_tier: "Standard"
    wordpress_oci_media_bucket: "{{ vault_oci_bucket_name }}"
    wordpress_oci_backup_bucket: "{{ vault_oci_backup_bucket_name }}"
    wordpress_object_storage_bucket: "{{ vault_oci_bucket_name }}"
    wordpress_object_storage_region: "us-ashburn-1"
    wordpress_object_storage_path_prefix: "wp-content/uploads"

    # ========================================================================
    # SSL/TLS
    # ========================================================================
    wordpress_enable_ssl: true
    wordpress_use_letsencrypt: true
    wordpress_letsencrypt_email: "ssl@example.com"
    wordpress_ssl_protocols: "TLSv1.2 TLSv1.3"

    # ========================================================================
    # Email - SendGrid
    # ========================================================================
    wordpress_smtp_enabled: true
    wordpress_smtp_provider: "sendgrid"
    wordpress_smtp_host: "smtp.sendgrid.net"
    wordpress_smtp_port: 587
    wordpress_smtp_user: "apikey"
    wordpress_smtp_password: "{{ vault_sendgrid_api_key }}"
    wordpress_smtp_from_email: "noreply@example.com"
    wordpress_smtp_encryption: "tls"

    # ========================================================================
    # Performance Optimization
    # ========================================================================
    wordpress_opcache_enable: true
    wordpress_opcache_memory: "256"
    wordpress_opcache_validate_timestamps: "0"

    wordpress_image_optimization_enabled: true
    wordpress_webp_enabled: true

    # ========================================================================
    # Security
    # ========================================================================
    wordpress_enable_fail2ban: true
    wordpress_configure_firewall: true
    wordpress_disable_file_edit: true
    wordpress_force_ssl_admin: true

    # OCI Security Lists (firewall rules)
    wordpress_allowed_ips:
      - "10.0.0.0/8"  # VCN network

    # ========================================================================
    # Backups to OCI Object Storage
    # ========================================================================
    wordpress_enable_backups: true
    wordpress_backup_dir: "/var/backups/wordpress"
    wordpress_backup_retention_days: 30
    wordpress_backup_to_cloud: true
    wordpress_backup_cloud_provider: "oci_storage"
    wordpress_backup_cloud_bucket: "{{ vault_oci_backup_bucket_name }}"

    # ========================================================================
    # Monitoring & Logging
    # ========================================================================
    wordpress_enable_logging: true
    wordpress_log_dir: "/var/log/wordpress"
    wordpress_logrotate_enabled: true

    # ========================================================================
    # Plugins
    # ========================================================================
    wordpress_plugins:
      - name: "wordfence"
        version: "latest"
        state: "present"
      - name: "redis-cache"
        version: "latest"
        state: "present"
      - name: "wp-mail-smtp"
        version: "latest"
        state: "present"
      - name: "wordpress-seo"
        version: "latest"
        state: "present"
      - name: "updraftplus"
        version: "latest"
        state: "present"
      - name: "wp-super-cache"
        version: "latest"
        state: "present"

    # ========================================================================
    # Themes
    # ========================================================================
    wordpress_themes:
      - name: "astra"
        version: "latest"
        state: "present"
        activate: true

  roles:
    - role: thomasvincent.wordpress_enterprise
