---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: rhel-8
    image: rockylinux:8
    dockerfile: ../default/Dockerfile.j2
    pre_build_image: false
    command: sleep infinity
    privileged: false
  
  - name: rhel-9
    image: rockylinux:9
    dockerfile: ../default/Dockerfile.j2
    pre_build_image: false
    command: sleep infinity
    privileged: false

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/../
  inventory:
    host_vars:
      rhel-8:
        ansible_python_interpreter: /usr/bin/python3
      rhel-9:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    prepare: prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: verify.yml
  lint:
    name: ansible-lint
    enabled: false  # Already done in CI

verifier:
  name: ansible

scenario:
  name: rhel
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
